services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "ricko229"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "Derrick229..."
      - key: N8N_PORT
        value: "5678"
      - key: WEBHOOK_TUNNEL_URL
        value: "https://ton-n8n.onrender.com"
